# Generated by Django 4.2.6 on 2023-10-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseapplication'),
        ('profiles', '0005_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Учитель'), ('manager', 'Менеджер')], default='student', max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Учитель'), ('manager', 'Менеджер')], default='student', max_length=25),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Учитель'), ('manager', 'Менеджер')], default='student', max_length=25),
        ),
    ]
