# Generated by Django 4.2.6 on 2023-10-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_manager_polymorphic_ctype_student_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='student',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='polymorphic_ctype',
        ),
    ]
