version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    expose:
      - "6379"

  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - web
      - redis
    environment:
      # Настройки для Celery
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - web
      - redis
    environment:
      # Настройки для Celery Beat
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

volumes:
  postgres_data:

