# Generated by Django 4.2.6 on 2023-10-30 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseapplication'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
