# Generated by Django 4.2.6 on 2023-10-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_month_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-due_date'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'ordering': ['student', 'homework'], 'verbose_name': 'Оценка за ДЗ', 'verbose_name_plural': 'Оценки за ДЗ'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['week'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['course'], 'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяцы'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['student', 'completed'], 'verbose_name': 'Прогресс студента', 'verbose_name_plural': 'Прогресс студента'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['month'], 'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
    ]
