# Generated by Django 4.2.6 on 2023-10-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_month_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
