# Generated by Django 4.2.6 on 2023-10-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_manager_polymorphic_ctype_and_more'),
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver_type',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='receiver_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='profiles.manager'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='profiles.student'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='receiver_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='profiles.teacher'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='sender_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profiles.manager'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profiles.student'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='sender_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profiles.teacher'),
        ),
    ]
