# Generated by Django 4.2.6 on 2023-10-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_messages', '0002_remove_privatemessage_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver_manager',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver_student',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='receiver_teacher',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender_manager',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender_student',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender_teacher',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
