# Generated by Django 4.2.6 on 2023-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_remove_privatemessage_receiver_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
